//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringConverter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringConverter.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Decoder.
        /// </summary>
        internal static string AESDecoder {
            get {
                return ResourceManager.GetString("AESDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES Encoder.
        /// </summary>
        internal static string AESEncoder {
            get {
                return ResourceManager.GetString("AESEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Decoder.
        /// </summary>
        internal static string Base64Decoder {
            get {
                return ResourceManager.GetString("Base64Decoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Encoder.
        /// </summary>
        internal static string Base64Encoder {
            get {
                return ResourceManager.GetString("Base64Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary To Text.
        /// </summary>
        internal static string BinaryToText {
            get {
                return ResourceManager.GetString("BinaryToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoder with Custom Password.
        /// </summary>
        internal static string DecoderCustomPassword {
            get {
                return ResourceManager.GetString("DecoderCustomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DES Decoder.
        /// </summary>
        internal static string DESDecoder {
            get {
                return ResourceManager.GetString("DESDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DES Encoder.
        /// </summary>
        internal static string DESEncoder {
            get {
                return ResourceManager.GetString("DESEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder with Custom Password.
        /// </summary>
        internal static string EncoderCustomPassword {
            get {
                return ResourceManager.GetString("EncoderCustomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoders / Decoders.
        /// </summary>
        internal static string EncodersDecoders {
            get {
                return ResourceManager.GetString("EncodersDecoders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HASH / MESSAGE DIGEST ALGORITHMS.
        /// </summary>
        internal static string HASHMESSAGE {
            get {
                return ResourceManager.GetString("HASHMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex Decoder.
        /// </summary>
        internal static string HexDecoder {
            get {
                return ResourceManager.GetString("HexDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex Encoder.
        /// </summary>
        internal static string HexEncoder {
            get {
                return ResourceManager.GetString("HexEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Decoder.
        /// </summary>
        internal static string HtmlDecoder {
            get {
                return ResourceManager.GetString("HtmlDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html Encoder.
        /// </summary>
        internal static string HtmlEncoder {
            get {
                return ResourceManager.GetString("HtmlEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Case String.
        /// </summary>
        internal static string LowerCaseString {
            get {
                return ResourceManager.GetString("LowerCaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 Hash.
        /// </summary>
        internal static string MD5Hash {
            get {
                return ResourceManager.GetString("MD5Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORSE.
        /// </summary>
        internal static string Morse {
            get {
                return ResourceManager.GetString("Morse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morse Decoder.
        /// </summary>
        internal static string MorseDecoder {
            get {
                return ResourceManager.GetString("MorseDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morse Encoder.
        /// </summary>
        internal static string MorseEncoder {
            get {
                return ResourceManager.GetString("MorseEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse String.
        /// </summary>
        internal static string ReverseString {
            get {
                return ResourceManager.GetString("ReverseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Decoder.
        /// </summary>
        internal static string RsaDecoded {
            get {
                return ResourceManager.GetString("RsaDecoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Encoder.
        /// </summary>
        internal static string RsaEncoded {
            get {
                return ResourceManager.GetString("RsaEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1 Hash.
        /// </summary>
        internal static string SHA1Hash {
            get {
                return ResourceManager.GetString("SHA1Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA256 Hash.
        /// </summary>
        internal static string SHA256Hash {
            get {
                return ResourceManager.GetString("SHA256Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA512 Hash.
        /// </summary>
        internal static string SHA512Hash {
            get {
                return ResourceManager.GetString("SHA512Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRING FUNCTIONS.
        /// </summary>
        internal static string STRINGFUNCTIONS {
            get {
                return ResourceManager.GetString("STRINGFUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT STYLES.
        /// </summary>
        internal static string TextStyle {
            get {
                return ResourceManager.GetString("TextStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to ASCII.
        /// </summary>
        internal static string TextToAscii {
            get {
                return ResourceManager.GetString("TextToAscii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text To Binary.
        /// </summary>
        internal static string TextToBinary {
            get {
                return ResourceManager.GetString("TextToBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Case String.
        /// </summary>
        internal static string TitleCaseString {
            get {
                return ResourceManager.GetString("TitleCaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Decoder.
        /// </summary>
        internal static string UnicodeDecoder {
            get {
                return ResourceManager.GetString("UnicodeDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode Encoder.
        /// </summary>
        internal static string UnicodeEncoder {
            get {
                return ResourceManager.GetString("UnicodeEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Case String.
        /// </summary>
        internal static string UpperCaseString {
            get {
                return ResourceManager.GetString("UpperCaseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Decoder.
        /// </summary>
        internal static string UrlDecoder {
            get {
                return ResourceManager.GetString("UrlDecoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Encoder.
        /// </summary>
        internal static string UrlEncoder {
            get {
                return ResourceManager.GetString("UrlEncoder", resourceCulture);
            }
        }
    }
}
